import type { Metadata } from "next"
import { Geist_Mono } from "next/font/google"
import "./globals.css"

const JetBrains = Geist_Mono({ subsets: ["latin"], weight: "400" })

export const metadata: Metadata = {
	title: "mrtnz",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang="en"
			className="bg-black text-white"
		>
			<body className={`${JetBrains.className} min-h-dvh p-8`}>{children}</body>
		</html>
	)
}
