import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "./globals.css"

const montserrat = Montserrat({ subsets: ["latin"], weight: "500" })

export const metadata: Metadata = {
	title: "mrtnz",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang="en"
			className="bg-black text-white"
		>
			<body className={`${montserrat.className} min-h-dvh p-8`}>
				{children}
			</body>
		</html>
	)
}
